name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "${{ env.GITHUB_ACTION }}"
    - name: Run a multi-line script
      run: |
        echo "${{ env.GITHUB_ACTION }}"
        echo "${{ env.GITHUB_REF }}"
        echo "${{ env.GITHUB_BASE_REF }}"
        echo "${{ env.GITHUB_HEAD_REF }}"
