name: CI

on: [push, pull_request, release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: cat /home/runner/work/_temp/_github_workflow/event.json
    - name: print env
      run: env
    - name: Run a multi-line script
      shell: bash
      run: |
        echo "${GITHUB_ACTION}"
        echo "${GITHUB_ACTIONS}"
        echo "${GITHUB_REF}"
        echo "${GITHUB_BASE_REF}"
        echo "${GITHUB_HEAD_REF}"
        echo ~
        echo "$HOME"
        echo "tilde" && ls ~
        echo "home" && ls "$HOME"
